cities/urls.py
from django.contrib import admin
from django.urls import path

from cities.views import *

app_name = 'cities'

urlpatterns = [
    path('', home, name='home'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    # path('delete/<int:pk>/', city_delete, name='delete'),
    path('add/', CityCreateView.as_view(), name='create'),
]

trains/urls.py
from django.contrib import admin
from django.urls import path

from trains.views import *

app_name = 'trains'

urlpatterns = [
    path('', home, name='home'),
    path('detail/<int:pk>/', TrainDetailView.as_view(), name='detail'),
    # path('update/<int:pk>/', TrainUpdateView.as_view(), name='update'),
    # # path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    # path('delete/<int:pk>/', city_delete, name='delete'),
    # path('add/', CityCreateView.as_view(), name='create'),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from travel.views import home, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cities/', include(('cities.urls', 'cities'))),
    path('trains/', include(('trains.urls', 'trains'))),
    path('home/', home, name='home'),
    path('about/', about),
]

cities/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Город')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trains:detail', kwargs={'pk':self.pk})

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Городa'
        ordering = ['name']

trains/models.py
from django.core.exceptions import ValidationError
from django.db import models

from cities.models import City

# Create your models here.
class Train(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Номер поезда')
    travel_time = models.PositiveSmallIntegerField(verbose_name='Время в пути')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='from_city_set', verbose_name='Из какога города')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='to_city_set', verbose_name='В какой город')

    def __str__(self):
        return f'Поезд №{self.name} из города {self.from_city}'

    def clean(self):
        if self.from_city == self.to_city:
            raise ValidationError('Изменить город прибытия')
        qs = Train.objects.filter(from_city=self.from_city, to_city=self.to_city, travel_time=self.travel_time).exclude(pk=self.pk)
        if qs.exists() :
            raise ValidationError('Измените время в пути')

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Поезд'
        verbose_name_plural = 'Поезда'
        ordering = ['name']

cities/forms.py
from django import forms

from cities.models import City


class CityForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Введите название города',
    }), label='Город')

    class Meta:
        model = City
        fields = ('name', )

cities/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from cities.models import City
from cities.forms import CityForm

__all__ = (
    'home',
    'CityDetailView',
    'CityCreateView',
    'CityUpdateView',
    'CityDeleteView',
)

from django.urls import reverse_lazy

from django.views.generic import DetailView, CreateView, UpdateView, DeleteView


def home(request):
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
    form = CityForm()
    qs = City.objects.all()
    lst = Paginator(qs, 2)
    page_number = request.GET.get('page')
    page_obj = lst.get_page(page_number)
    context = {'page_obj':page_obj, 'form':CityForm}
    return render(request, 'cities/home.html', context)

class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = 'cities/detail.html'

class CityCreateView(SuccessMessageMixin, CreateView):
    model = City
    form_class = CityForm
    template_name = 'trains/create.html'
    success_url = reverse_lazy('trains:home')
    success_message = "Город успешно создан"

class CityUpdateView(SuccessMessageMixin, UpdateView):
    model = City
    form_class = CityForm
    template_name = 'trains/update.html'
    success_url = reverse_lazy('trains:home')
    success_message = "Город успешно отредактирован"

class CityDeleteView(DeleteView):
    model = City
    success_url = reverse_lazy('trains:home')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

# def city_delete(request, pk):
#     city = get_object_or_404(City, id=pk)
#     city.delete()
#     form = CityForm()
#     qs = City.objects.all()
#     lst = Paginator(qs, 2)
#     page_number = request.GET.get('page')
#     page_obj = lst.get_page(page_number)
#     context = {'page_obj': page_obj, 'form': CityForm}
#     return render(request, 'trains/home.html', context)

trains/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from trains.models import Train
# from trains.forms import TrainForm

__all__ = (
    'home',
    'TrainDetailView',
    # 'TrainCreateView',
    # 'TrainUpdateView',
    # 'Train_delete'
)

from django.urls import reverse_lazy

from django.views.generic import DetailView, CreateView, UpdateView, DeleteView


def home(request):
    # if request.method == 'POST':
    #     form = TrainForm(request.POST)
    #     if form.is_valid():
    #         print(form.cleaned_data)
    #         form.save()
    # form = TrainForm()
    qs = Train.objects.all()
    lst = Paginator(qs, 2)
    page_number = request.GET.get('page')
    page_obj = lst.get_page(page_number)
    context = {'page_obj':page_obj}
    return render(request, 'trains/home.html', context)

class TrainDetailView(DetailView):
    queryset = Train.objects.all()
    template_name = 'trains/detail.html'
#
# class TrainCreateView(SuccessMessageMixin, CreateView):
#     model = Train
#     form_class = TrainForm
#     template_name = 'trains/create.html'
#     success_url = reverse_lazy('trains:home')
#     success_message = "Город успешно создан"
#
# class TrainUpdateView(SuccessMessageMixin, UpdateView):
#     model = Train
#     form_class = TrainForm
#     template_name = 'trains/update.html'
#     success_url = reverse_lazy('trains:home')
#     success_message = "Город успешно отредактирован"
#
# # class TrainDeleteView(DeleteView):
# #     model = Train
# #     success_url = reverse_lazy('trains:home')
# #
# #     def get(self, *args, **kwargs):
# #         return self.post(*args, **kwargs)
#
# def Train_delete(request, pk):
#     Train = get_object_or_404(Train, id=pk)
#     Train.delete()
#     form = TrainForm()
#     qs = Train.objects.all()
#     lst = Paginator(qs, 2)
#     page_number = request.GET.get('page')
#     page_obj = lst.get_page(page_number)
#     context = {'page_obj': page_obj, 'form': TrainForm}
#     return render(request, 'trains/home.html', context)

travel/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

cities/templates/cities/detail.html
{% extends 'base.html' %}

{% block title %}
Город - {{ object.name }}
{% endblock %}

{% block content %}
<h1> Название города: </h1>
<div class="row">
    <div class="col-md">
        <p>{{ object.name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <a href="{% url 'cities:home' %}">
            <button class="btn btn-light">
                Назад к списку
            </button>
        </a>
    </div>
</div>
{% endblock %}

cities/templates/cities/home.html
{% extends 'base.html' %}

{% block title %}
Список городов
{% endblock %}

{% block content %}
<h1> Список городов </h1>
<div class="row">
    <div class="col-md-8 mx-auto my-2">
        <table class="table table-striped">
        {% for object in page_obj %}
            <tr>
                <td>
                    <a href="{% url 'cities:detail' pk=object.pk %}">{{ object.name }}</a>
                </td>
                <td>
                    <a href="{% url 'cities:update' pk=object.pk %}">
                        <button class="btn btn-primary">
                            Редактировать
                        </button></a>
                </td>
                <td>
                    <a href="{% url 'cities:delete' pk=object.id %}">
                        <button class="btn btn-danger">
                            Удалить
                        </button></a>
                </td>
            </tr>
        {% endfor %}
        </table>
    <a href="{% url 'cities:create' %}" class="btn btn-primary">Добавить город</a>
    </div>
</div>



<nav aria-label="Page navigation ">
  <ul class="pagination justify-content-center">
    <li class="page-item">
        {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        {% endif %}
    </li>
        {% for page in page_obj.paginator.page_range %}
                <li class="page-item {% if page == page_obj.number %} active {% endif %}">
                    <a class="page-link" href="?page={{page}}">
                        {{ page }}
                    </a>
                </li>
        {% endfor %}
    <li class="page-item">
        {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
                <span class="sr-only">Next</span>
                <span aria-hidden="true">&raquo;</span>
            </a>
        {% endif %}
    </li>
  </ul>
</nav>


{% endblock %}

templates/about.html
{% extends 'base.html' %}

{% block title %}
About page
{% endblock %}

{% block content %}
<h1> About page </h1>
{% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'trains:home' as trains_home_url %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg container" style="background-color: #e3f2fd">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">FindRoute</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == cities_home_url %} active {% endif %}" aria-current="page" href="{% url 'cities:home' %}">Города</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == trains_home_url %} active {% endif %}" aria-current="page" href="{% url 'trains:home' %}">Поезда</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div class="container">
      <div class="row" row>
        <div class="col-md-8 mx-auto my-2">
          {% if messages %}
              {% for message in messages %}
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                      {{ message }}
                    </div>
                  {% endif %}
              {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
      <div class="container">
        {% block content %}{% endblock %}
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{action}}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"  class=" btn btn-primary">{{ button }}</button>
        </form>
    </div>
</div>

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home page
{% endblock %}

{% block content %}
<h1> Home page </h1>
{% endblock %}

trains/templates/trains/create.html
{% extends 'base.html' %}

{% block title %}
Создание города
{% endblock %}

{% block content %}
<h1> Создание города </h1>
{% include 'form.html' with button='Создать' %}
{% endblock %}

trains/templates/trains/delete.html
{% extends 'base.html' %}

{% block title %}
Удаление города
{% endblock %}

{% block content %}
<h1> Удаление города </h1>
<p>{{ object }}</p>
{% include 'form.html' with button='Удалить' %}
{% endblock %}

trains/templates/trains/detail.html
{% extends 'base.html' %}

{% block title %}
Город - {{ object.name }}
{% endblock %}

{% block content %}
<h1> Название поезда: </h1>
<div class="row">
    <table class="table table-striped">
            <tr>
                <th>Номер</th>
                <th>Откуда</th>
                <th>Куда</th>
                <th>Время в пути</th>
            </tr>
            <tr>
                <td>
                    <a href="{% url 'trains:detail' pk=object.id %}">{{ object.name }}</a>
                </td>
                <td>{{ object.from_city }}</td>
                <td>{{ object.to_city }}</td>
                <td>{{ object.travel_time }}</td>
            </tr>
        </table>
</div>
<div class="row">
    <div class="col-md-4">
        <a href="{% url 'trains:home' %}">
            <button class="btn btn-light">
                Назад к списку
            </button>
        </a>
    </div>
</div>
{% endblock %}

trains/templates/trains/home.html
{% extends 'base.html' %}

{% block title %}
Список поездов
{% endblock %}

{% block content %}
<h1> Список поездов </h1>
<div class="row">
    <div class="col-md-8 mx-auto my-2">
        <table class="table table-striped">
            <tr>
                <th>Номер</th>
                <th>Откуда</th>
                <th>Куда</th>
                <th>Время в пути</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
        {% for object in page_obj %}
            <tr>
                <td>
                    <a href="{% url 'trains:detail' pk=object.id %}">{{ object.name }}</a>
                </td>
                <td>{{ object.from_city }}</td>
                <td>{{ object.to_city }}</td>
                <td>{{ object.travel_time }}</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        {% endfor %}
        </table>
    </div>
</div>



<nav aria-label="Page navigation ">
  <ul class="pagination justify-content-center">
    <li class="page-item">
        {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        {% endif %}
    </li>
        {% for page in page_obj.paginator.page_range %}
                <li class="page-item {% if page == page_obj.number %} active {% endif %}">
                    <a class="page-link" href="?page={{page}}">
                        {{ page }}
                    </a>
                </li>
        {% endfor %}
    <li class="page-item">
        {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
                <span class="sr-only">Next</span>
                <span aria-hidden="true">&raquo;</span>
            </a>
        {% endif %}
    </li>
  </ul>
</nav>


{% endblock %}

trains/templates/trains/update.html
{% extends 'base.html' %}

{% block title %}
Редактировать город
{% endblock %}

{% block content %}
<h1> Редактировать город </h1>
{% include 'form.html' with button='Редактировать' %}
{% endblock %}